import os
from dotenv import load_dotenv

load_dotenv(".env.local")

KEYCLOAK_HOST = os.getenv("KEYCLOAK_HOST")
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM")

NEXTCLOUD_KEYCLOAK_CLIENT_ID = os.getenv("NEXTCLOUD_KEYCLOAK_CLIENT_ID")
NEXTCLOUD_KEYCLOAK_CLIENT_SECRET = os.getenv("NEXTCLOUD_KEYCLOAK_CLIENT_SECRET")

NEXTCLOUD_URL = os.getenv("NEXTCLOUD_URL")
NEXTCLOUD_ROOT_PATH = os.getenv("NEXTCLOUD_ROOT_PATH")

DAVI_KEYCLOAK_CLIENT_ID = os.getenv("DAVI_KEYCLOAK_CLIENT_ID")
DAVI_KEYCLOAK_CLIENT_SECRET = os.getenv("DAVI_KEYCLOAK_CLIENT_SECRET")
